"""add images to solutions

Revision ID: 49f0a8ce8856
Revises: e953226ccd68
Create Date: 2025-11-16 21:54:40.646043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f0a8ce8856'
down_revision = 'e953226ccd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_image',
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('fk_solution_image_image_id_image'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solution_id'], ['solution.id'], name=op.f('fk_solution_image_solution_id_solution'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('solution_id', 'image_id', name=op.f('pk_solution_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solution_image')
    # ### end Alembic commands ###
