"""solution approval

Revision ID: 8454ddd831b9
Revises: 53f9615dfcc3
Create Date: 2025-12-11 12:59:45.514788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8454ddd831b9'
down_revision = '53f9615dfcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution', schema=None) as batch_op:
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
