"""add order to images

Revision ID: 9629633a14fa
Revises: aeb01717f220
Create Date: 2025-11-21 23:18:54.573246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9629633a14fa'
down_revision = 'aeb01717f220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_post_image_image_id_image'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_image_image_id_image'), 'image', ['image_id'], ['id'])

    with op.batch_alter_table('solution_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_solution_image_image_id_image'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_solution_image_image_id_image'), 'image', ['image_id'], ['id'])

    # ### end Alembic commands ###
    post_image = sa.table(
        'post_image',
        sa.column('post_id', sa.Integer()),
        sa.column('image_id', sa.String()),
        sa.column('id', sa.Integer()),
        sa.column('order', sa.Integer())
    )
    solution_image = sa.table(
        'solution_image',
        sa.column('solution_id', sa.Integer()),
        sa.column('image_id', sa.String()),
        sa.column('id', sa.Integer()),
        sa.column('order', sa.Integer())
    )

    connection = op.get_bind()

    post_rows = connection.execute(sa.select(post_image.c.post_id, post_image.c.image_id)).fetchall()
    for idx, (post_id, image_id) in enumerate(post_rows, start=1):
        connection.execute(
            post_image.update()
            .where(sa.and_(post_image.c.post_id == post_id, post_image.c.image_id == image_id))
            .values(id=idx, order=idx)
        )

    solution_rows = connection.execute(sa.select(solution_image.c.solution_id, solution_image.c.image_id)).fetchall()
    for idx, (solution_id, image_id) in enumerate(solution_rows, start=1):
        connection.execute(
            solution_image.update()
            .where(sa.and_(solution_image.c.solution_id == solution_id, solution_image.c.image_id == image_id))
            .values(id=idx, order=idx)
        )

    with op.batch_alter_table('post_image', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('order', existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table('solution_image', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('order', existing_type=sa.INTEGER(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_solution_image_image_id_image'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_solution_image_image_id_image'), 'image', ['image_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('order')
        batch_op.drop_column('id')

    with op.batch_alter_table('post_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_image_image_id_image'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_image_image_id_image'), 'image', ['image_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('order')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
