"""locality store coords instead of names

Revision ID: aeb01717f220
Revises: 49f0a8ce8856
Create Date: 2025-11-16 22:25:19.164040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb01717f220'
down_revision = '49f0a8ce8856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
