"""active device

Revision ID: e8768fd981d4
Revises: d7bdc22a0db6
Create Date: 2025-01-28 17:58:44.438005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8768fd981d4'
down_revision = 'd7bdc22a0db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_jti', sa.String(length=36), nullable=False),
    sa.Column('access_jti', sa.String(length=36), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_device_access_jti'), ['access_jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_active_device_refresh_jti'), ['refresh_jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_device_refresh_jti'))
        batch_op.drop_index(batch_op.f('ix_active_device_access_jti'))

    op.drop_table('active_device')
    # ### end Alembic commands ###
