"""add images to posts

Revision ID: e953226ccd68
Revises: 09e6d5e6ee00
Create Date: 2025-11-16 21:29:20.984499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e953226ccd68'
down_revision = '09e6d5e6ee00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_image',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], name=op.f('fk_post_image_image_id_image'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_image_post_id_post'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'image_id', name=op.f('pk_post_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_image')
    # ### end Alembic commands ###
