"""locality

Revision ID: ed1c64f54ed2
Revises: ab98e4dfe378
Create Date: 2025-11-09 00:59:47.747370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1c64f54ed2'
down_revision = 'ab98e4dfe378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locality')),
    sa.UniqueConstraint('osm_id', name=op.f('uq_locality_osm_id'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('locality_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_locality_id_locality'), 'locality', ['locality_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_locality_id_locality'), type_='foreignkey')
        batch_op.drop_column('locality_id')
        batch_op.drop_column('created_at')

    op.drop_table('locality')
    # ### end Alembic commands ###
